// Crear productos deportivos
const products = [
  {id: 1, name: 'Peluche abeja', price:36000,img: './image/abeja.jpeg'},
  {id: 2, name: 'Bucket hat Cinnamoroll', price:38000,img: './image/cinamonroll.jpeg'},
  {id: 3, name: 'Peluche Hello Kitty', price:30000,img: './image/hellokitty.jpeg'},
  {id: 4, name: 'Frog bucket hat', price:38000,img: './image/bucketRana.jpeg'},
  {id: 5, name: 'Peluche Ballena', price:36000,img: './image/ballena.jpeg'},
  {id: 6, name: 'Frog hat crochet', price:40000,img: './image/gorroRana.jpeg'},
  {id: 7, name: 'Peluche conejo bicolor', price:45000,img: './image/conejoBicolor.jpeg'},
  {id: 8, name: 'Top Antonella', price:38000,img: './image/top.jpeg'},
  {id: 9, name: 'Peluche mapache Winnie', price:48000,img: './image/mapache.jpeg'},
  {id: 10, name: 'Top Lola', price: 40000,img: './image/topLola.jpeg'},
  {id: 11, name: 'Peluche conejo rosa', price:48000,img: './image/conejoRosa.jpeg'},
  {id: 12, name: 'Cardigan Daisy', price:80000,img: './image/cardiganFlor.jpeg'},
  {id: 13, name: 'Peluche paquita la gallina', price:28000,img: './image/gallina.jpeg'},
  {id: 14, name: 'Flor girasol', price:16000,img: './image/girasol.jpeg'},
  {id: 15, name: 'Peluche vaquita Lucy', price:48000,img: './image/vaquita.jpeg'},
  {id: 16, name: 'Top Bella', price:40000,img: './image/topBella.jpeg'},
  {id: 17, name: 'Peluche ajolote', price:30000,img: './image/ajolote.jpeg'},
  {id: 18, name: 'Cardigan JW Anderson', price:120000,img: './image/cardiganHarry.jpeg'},
  {id: 19, name: 'Peluche conejo Thomas', price:48000,img: './image/conejoGafas.jpeg'},
  {id: 20, name: 'Summer Top', price:50000,img: './image/summerTop.jpeg'},
  {id: 21, name: 'Bucket hat Daisy', price:35000,img: './image/bucket.jpeg'},
  {id: 22, name: 'Aretes de cereza', price:12000,img: './image/cereza.jpeg'},
  {id: 23, name: 'Peluche pollito', price:28000,img: './image/pollito.jpeg'},
  {id: 24, name: 'Harper Top', price:45000,img: './image/harperTop.jpeg'},
  {id: 25, name: 'Peluche de Hongo', price:45000,img: './image/hongo.jpeg'},
  {id: 26, name: 'Top Marcella', price:50000,img: './image/topSencillo.jpeg'},
  {id: 27, name: 'Peluche tortuga Daisy', price:40000,img: './image/tortuga.jpeg'},
  {id: 28, name: 'Bolso Daisy', price:40000,img: './image/bolosFlor.jpeg'},
  {id: 29, name: 'Conejo Strawberry', price:48000,img: './image/conejoFresa.jpeg'},
  {id: 30, name: 'Bucket Hat Keroppi', price:40000,img: './image/hatRana.jpeg'},
];